### PR TITLE
add participant-Niyati

### PR DESCRIPTION
**Pull request by blackcrabb**
For #20

### CODE REVIEW

**Comment by blackcrabb** [comment]
i have updated the changes , you can check now.

**Comment by lisa761** [comment]
There seem to be no additional commits in this branch or they would have appeared here. I think you accidentally committed in your master branch. That commit needs to be in this branch for the PR to be merged. It would also be great if you could look up how to delete a pushed commit to remove that commit from master.  
You can do this by:
```sh
git reset HEAD^--hard
git push origin master --force
```
Once done, checkout to your current branch of the PR and then make the changes. If you do it on GitHub, make sure you are on this branch and not the master.
Have you finished the previous tasks?

**Comment by blackcrabb** [comment]
hey 
when i change the branch here , i can see the output but after then if open it in a fresh window , the changed branch disappears . i am not able to solve the issue.

**Comment by blackcrabb** [comment]
https://github.com/blackcrabb/Open-Source-Challenge/tree/blackcrabb-task2

**Comment by soumyaa1804** [comment]
@blackcrabb can you please attach the output of `git branch`?

**Comment by soumyaa1804** [comment]
> i have updated the changes , you can check now.

Did you push them after committing? And did you perform the [Task 2](https://github.com/ACM-IGDTUW/Open-Source-Challenge/issues/20) before submitting PR for task 3?

**Comment by blackcrabb** [comment]
I was going through task 2 and was going through some steps and i thought i missed some steps , 
i tried 
git fetch upstream and rebase and it added all the members.md i guess

**Comment by lisa761** [comment]
That's alright but we won't be able to merge this until you are done with task-2

**Comment by lisa761** [comment]
That's alright, you just have to remove the dot.

**Comment by lisa761** [comment]
Hi @blackcrabb, If you are running into trouble, feel free to ask here.

**Comment by blackcrabb** [comment]
https://github.com/blackcrabb/Open-Source-Challenge/tree/blackcrabb-task2/participants

**Comment by blackcrabb** [comment]
can you please check if i got it this time?

**Comment by blackcrabb** [comment]
Thanks , i can move to Task 3 right

**Comment by lisa761** [comment]
Yes, go ahead.

**Pull request merged**
