### PR TITLE
Created saloniankita.md

### PR DESCRIPTION
**Pull request by saloniankita**
I have created the styling in md file.
For #20 
Kindly review it.

### CODE REVIEW

**Comment by soumyaa1804** [comment]
@saloniankita you need to create the file inside `participants` directory. Kindly move your file there and add, commit and push again on the same branch.

**Comment by soumyaa1804** [comment]
Closing this one as #86 is merged.

**Comment by lisa761** [comment]
Hi @saloniankita, Just a suggestion, name your PRs more appropriate to the work it does. For example, here you opened this PR for task-3 but the name of your PR suggests that it does what is asked for in Task-2 (as that is where we asked to create a `<username>.md` file). We don't remember all the submissions, so doing this would help avoid confusion. Good work otherwise!

**Comment by saloniankita** [comment]
Sure. Will take care of that in future.

**Pull request closed without merging**
