### PR TITLE
Added GitHub link and removed a broken CSS link

### LINKED ISSUE #122: Added GitHub link and removed a broken CSS link
For #93
So, My small contribution to this awesome initiative is that I can add a GitHub and Instagram link in the footer.

### PR DESCRIPTION
**Pull request by Tarster**
closes #122  
So I had made the necessary changes:
1.) Now only Github Link is there.
2.) I had removed the broken link queryloader.css from the events.ejs file as the file is not present in the location.

### CODE REVIEW

**Comment by lisa761** [comment]
@Tarster, great work! Have you created an issue for this? If you have then please link this PR to it, or create one and then link this PR. Thanks!

**Comment by Tarster** [comment]
Hey,I had created a issue but I had closed it.However I had reopened it,so that this PR can be linked to it,However I don't know to link PR with the issue.

**Comment by lisa761** [comment]
Edit your description in this PR and add `closes #<your-issue-number>`.

**Comment by Tarster** [comment]
Done

**Comment by soumyaa1804** [comment]
@Tarster, we have merged the changes for Instagram and LinkedIn icons and they caused merge conflicts in your PR. Nothing to worry! You can resolve them as described [here](https://www.youtube.com/watch?v=JtIX3HJKwfo).

**Comment by Tarster** [comment]
Thanks,I again learned a new thing.By the way,I have removed the merge conflict.

**Comment by soumyaa1804** [comment]
Great! PR is good to go now! Cheers!

**Comment by soumyaa1804** [comment]
@Tarster, I just noticed that you added the link to this repository instead of the link to our organization [ACM-IGDTUW](https://github.com/ACM-IGDTUW). As this is merged now, I'll create a separate issue for change in URL. If you wish you can solve it. :)

**Pull request merged**
