### PR TITLE
add participant- Avinash

### PR DESCRIPTION
**Pull request by Avinash-1501**
For #20

### CODE REVIEW

**Comment by Avinash-1501** [comment]
Do I need to add demo.md, commit again and then create a pull request again?

**Comment by lisa761** [comment]
I suggest closing this one and working in a new branch and submit PR because its safer to not have that deleted file in history once we merge this PR. Make sure that you checkout to master before creating a new branch. You can do this by running `git checkout master`

**Comment by Avinash-1501** [comment]
shall I delete this branch create new one?

**Comment by lisa761** [comment]
Sure

**Comment by Avinash-1501** [comment]
I think I added the demo.md in this branch only along with the file I created. can you check this once

**Pull request merged**
