### PR TITLE
add participant-<mishra-aanchal>

### PR DESCRIPTION
**Pull request by mishra-aanchal**
For #20

### CODE REVIEW

**Comment by lisa761** [comment]
Hi @mishra-aanchal, The Task-2 asks you to create _new_ file and these information there. These changes are not supposed to be made to `demo.md` like in the screen shot you shared. In this PR, you seem to have successfully added the file. Are you still unable to make changes to do that file and save it?

**Comment by mishra-aanchal** [comment]
> Hi, @mishra-aanchal You haven't added the necessary information that was asked to be added. Please add them and push the commit again.

hello @lisa761 i guess i added the information my na,e.university,branch and year from the Notepad.

**Comment by mishra-aanchal** [comment]
> Hi @mishra-aanchal, The Task-2 asks you to create a _new_ file and these information there. The changes are not supposed to be made to `demo.md` like in the screen shot you shared. In this PR, you seem to have successfully added the file. Are you still unable to make changes to do that file and save it?

yes i was able to!
thankyou.

**Comment by lisa761** [comment]
So you will need to add the info in your file and then we can merge this PR. Currently, that file is empty.

**Comment by lisa761** [comment]
Hi @mishra-aanchal, if you need any help, feel free to ask.

**Comment by mishra-aanchal** [comment]
I had one doubt that how does the git bash actually work?
Adding to this, while installing git for windows we had 3 installations:
GUI, Command and bash! Then what are these for!?

**Comment by lisa761** [comment]
Hi, @mishra-aanchal here is the [link](https://stackoverflow.com/a/42332860/11943496) to reset your master. Make sure that you do this before creating another PR.

**Comment by soumyaa1804** [comment]
@mishra-aanchal, as @lisa761 said you first need to reset your master then it would be great if you do task 3 again. It won't be useful to commit to the same branch now.

**Comment by soumyaa1804** [comment]
Closing this one as a new PR is expected. Feel free to open in case of any discussion.

**Pull request closed without merging**
