### PR TITLE
styling

### PR DESCRIPTION
**Pull request by Avinash-1501**
#50

### CODE REVIEW

**Comment by Avinash-1501** [comment]
@lisa761 Thank you. I'll make necessary changes and submit again

**Comment by Avinash-1501** [comment]
@lisa761  I made necessary changes I think. Can you please verify.

**Comment by lisa761** [comment]
Great! If you don't wish to add anything, let us know and we will merge the PR.

**Comment by Avinash-1501** [comment]
Any suggestions on adding something.

**Comment by lisa761** [comment]
It wouldn't be fair for me to suggest anything, but its all about creativity and you can go wild! You can look through other merged PRs if you wish to do so and tell us when you are sure you want to submit.

**Comment by Avinash-1501** [comment]
Ok Thank You.

**Comment by Avinash-1501** [comment]
@lisa761 hey, I made some changes to my file and I think It is fine now to merge. Please check and proceed.

**Comment by Avinash-1501** [comment]
I think I did something wrong. I accidentally deleted a commit and now when I try to push the banch it is rejecting. What should I do

**Comment by lisa761** [comment]
While pushing you can use the force flag, that is: `git push origin styling-md-Avinash --force`

The force command will forcefully push any additional commits.

**Comment by Avinash-1501** [comment]
well that is ok, it worked. but what actually happened? I delete a commit and when i tried to push again it is shown as:
C:\Users\Avinash\Desktop\folder1\Open-Source-Challenge>git push origin styling-md-Avinash
To https://github.com/Avinash-1501/Open-Source-Challenge.git
 ! [rejected]        styling-md-Avinash -> styling-md-Avinash (non-fast-forward)
error: failed to push some refs to 'https://github.com/Avinash-1501/Open-Source-Challenge.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by soumyaa1804** [comment]
Can you attach the error message?

**Comment by Avinash-1501** [comment]
IMG_20200415_233520

**Comment by lisa761** [comment]
@Avinash-1501 what happened here is that you deleted the commit from your local branch, but that commit is still present on GitHub as you had pushed them previously. This causes the end points of your local and your forked branch to be different as the most recent commits are different. Due to that, GitHub just rejects allowing commits to be pushed. It says in the end `hint: git pull...`. If you use that here, like `git pull styling-md-Avinash` it pulls that branch from GitHub to your local the way it is on the fork. That should remove your deleted commit from your local repo as well.

**Comment by Avinash-1501** [comment]
@lisa761 Ok. Is it all ready to merge now? Or do I need to make any changes? 😃

**Comment by lisa761** [comment]
Its great.

**Pull request merged**
