### PR TITLE
Styling - Raksha

### PR DESCRIPTION
**Pull request by raksha009**
#50

### CODE REVIEW

**Comment by soumyaa1804** [comment]
@raksha009 Your file looks  like this right now:
image

It's completely fine and I have no issues with merging it but if you want you can bring `Branch` and `Year` on different lines and commit and push those changes again in the same branch.

**Comment by raksha009** [comment]
how to bring branch and year in different lines... i am not getting that part

**Comment by raksha009** [comment]
done

**Comment by soumyaa1804** [comment]
Great! You can see your file [here](https://github.com/raksha009/Open-Source-Challenge/blob/styling-md-Raksha-Jain/participants/raksha009.md). If this was what you intended we are good to merge it. Let us know!

**Comment by raksha009** [comment]
done @soumyaa1804

**Pull request merged**
