### PR TITLE
Styling md omkaragrawal

### LINKED ISSUE #50: Task 3: Some Markdown Styling
In the last [Task](https://github.com/ACM-IGDTUW/Open-Source-Challenge/issues/20), you made your first PR by creating a markdown file. This Task of The Open Source Challenge will revolve around learning some nitty-gritties of the Markdown language. What you will do is take your `<name>.md` file, and add some amount of Markdown styling to show us how much of it you have grasped. Once done, you create a pull request to submit your task. Make sure you have completed [Task 2](https://github.com/ACM-IGDTUW/Open-Source-Challenge/issues/20 ) before moving ahead.

The task is as follow:

1. Update your Fork.

Now, your fork must be pretty behind, since yesterday itself, we had a lot of merged pull requests. This is because when you update your main repository, it does not automatically update the forked repositories. For that, you have to manually update it. To see just how behind your repository is, go to your forked repository page on GitHub. You will see a message like `This branch is <some> commits behind ACM-IGDTUW:Master`.  
To update, follow these set of commands. Some of you must have done this in the previous task as well.
```sh
cd Open-Source-Challenge
git checkout master
git fetch upstream
git rebase upstream/master
git push origin master
````

> What these set of commands do is, fetch the upstream, which is the original Open-Source-Challenge repository. Then it overwrites the master branch of your origin, which is your local forked version, using the master branch of upstream. Once the changes have been made to your local master, you need to push them to GitHub and that's what the last command does.

2. Delete your old branch and create a new one to work for this task.

Inside the project directory, run:
```sh
git checkout master
git -D <your-previous-branch-name>
git checkout -b styling-md-<your-name>
```
This creates a new branch. For example, `styling-md-john12` for us.  
> You can delete this branch from your fork on GitHub as well. To do this, go to your fork on GitHub and click on the branches button at the top. Then click on the delete button next to the branch you want to delete. Do not accidentally delete the `master` branch.

3. Open the markdown file that you created in the previous task and add some styling.  

To do so, you might want to add some extra information so that you can add styling to those. This information can be anything that you wish to add or are okay with everyone knowing about. For example, you could write some of your achievements.  

You can refer to this [Markdown Cheat-sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for styling.  

You may want to preview what your markdown code looks like after compilation, so you may start writing your code in this online markdown previewer, [StackEdit](https://stackedit.io/app#) and then when you are satisfied with the styling you can copy and paste your code into your markdown file.

4. Once you are done with styling, submit a PR using the steps we mentioned in the last task.
___________________________________________

Done! We will see your PR as a submission. This task will have an evaluation based on how well you have grasped Markdown. As one of the important factors of open source is to be able to find and do things on your own, this Task will be a great way to move in that direction.  

Remember that any technical doubts will be answered only through the issues created in the repository. This is an important rule that you must follow.

### PR DESCRIPTION
**Pull request by Omkaragrawal**
image

Resolve #50

### CODE REVIEW

**Comment by soumyaa1804** [comment]
@Omkaragrawal, you have added the wrong origin repository. I just noticed your origin is `https://github.com/omkaragrawal/Open-Source-Challenge.git` instead of `https://github.com/Omkaragrawal/Open-Source-Challenge.git`. Notice the capital `O` in Omkaragrawal. You can see [here](https://github.com/ACM-IGDTUW/Open-Source-Challenge/issues/11#issuecomment-613046447).

**Comment by soumyaa1804** [comment]
Also, have committed to master which you should not do at all.

**Comment by Omkaragrawal** [comment]
@soumyaa1804  I believe, even though a mistake, it did come in sync with the proper git repo of **"Omkaragarawal"**. The image below would clear out things for you. Also the push command was given in VSCode's integrated terminal, and I forgot to take a screenshot of it. Nonetheless my PR request should be correct. Please have a look once again, and if wrong, can you please point out the exact mistake. that would be a great help.

image

**Comment by lisa761** [comment]
Hi @Omkaragrawal, since you have made a successful submission of Task-2 I am guessing somehow your origin is correct. But you seem to have merged a PR in your forked repo from ImgBot used to decrease the size of the images. Since this was an unnecessary change, it adds a lot of unrelated commits to this PR as you can see here itself. I would suggest resetting your master using the upstream by following [this](https://stackoverflow.com/a/42332860) step by step and creating a new PR with a different branch. Try to avoid merging anything or adding any commits to your master branch.

**Comment by soumyaa1804** [comment]
As you can see in the `files changed` you have 15 changed files. A successful submission would require only one file change.

**Pull request closed without merging**
