### PR TITLE
markdown added by aayushi

### PR DESCRIPTION
**Pull request by aayushibansal2001**
markdown styling added
For #50

### CODE REVIEW

**Comment by aayushibansal2001** [comment]
Ya , i did them using enter but that didn't work. How can i put an enter
between the lines?

**Comment by lisa761** [comment]
You have to enter twice to introduce a new line in Markdown.

**Comment by lisa761** [comment]
Great!, so if you are done, let us know so we can merge this

**Comment by aayushibansal2001** [comment]
Yes, done!

**Pull request merged**
