### PR TITLE
add participant-vanshika

### PR DESCRIPTION
**Pull request by vkr-code**
Pls suggest changes..
For #50

### CODE REVIEW

**Comment by soumyaa1804** [comment]
@vkr-code The changes look great but can you make changes to only the file you created in task 2 and delete this file? Your previous file would be vkr-code.md in the `participants` directory.

**Comment by vkr-code** [comment]
Okay..thank you...I will do that.

**Comment by lisa761** [comment]
Hi @vkr-code, just a suggestion, name your PRs in a more appropriate way. For eg, this PR is for Task-3 but your title is the same as that you used for submission of Task-2. You could, for example, name this one as `Styling vkr-code.md`.

**Comment by vkr-code** [comment]
Ok,Thank you

**Comment by lisa761** [comment]
Closing this since it has been inactive for a while now. Feel free to reopen in case you want to continue working on this.

**Pull request closed without merging**
